# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1eedb52230f69992d8e4bb027ad932a779f12753ab7e5da2070938bcf1e275bf5aaa37332b9f703a6c4de61a7de1ecb5e836974da45e95ddc4343e1aea03e57e

test:
  secret_key_base: 9b6a3d37a7f42737d7a98e3ae1ff22af7c37994813b0bf16f9551933a1d3a682641545a59cd1fe8bf4412dd4d3e493f3f230bd0bd7ae7ef6d2f76f246c7c9676

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
